name: Build & Deploy Web
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build web --release --wasm --base-href "/the-radar/" --dart-define=SUPABASE_URL=https://wmadurjharulfyyzzyes.supabase.co --dart-define=SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtYWR1cmpoYXJ1bGZ5eXp6eWVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODk3NjAyODIsImV4cCI6MjEwNTMzNjI4Mn0.4YH34yOmSftElGBTcBLk2D2kmwqsYjJAkWHttjPcIGE
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
          publish_branch: web-deploy
